import { Trip } from "./types";

export const CITIES = ["Douala", "Yaoundé", "Bafoussam", "Kribi"];

export const TRIPS: Trip[] = [
  {
    id: "1",
    agency: "Général Express",
    code: "GE",
    color: "#1DB954",
    depH: "07:00",
    arrH: "10:30",
    dur: "3h30",
    depart: "Douala",
    arrive: "Yaoundé",
    depStop: "Gare Centrale",
    arrStop: "Gare Centrale",
    price: 5000,
    seats: 14,
    total: 32,
    rating: 4.2,
    reviews: 128,
    status: "open",
    amenities: ["❄️", "🧳"],
  },
  {
    id: "2",
    agency: "Buca Voyages",
    code: "BV",
    color: "#FF6B35",
    depH: "09:30",
    arrH: "13:00",
    dur: "3h30",
    depart: "Douala",
    arrive: "Yaoundé",
    depStop: "Gare de Yabassi",
    arrStop: "Mvog-Mbi",
    price: 4500,
    seats: 3,
    total: 32,
    rating: 4.8,
    reviews: 204,
    status: "urgent",
    amenities: ["❄️", "🧳", "🔌"],
  },
  {
    id: "3",
    agency: "Vatican Express",
    code: "VE",
    color: "#6C63FF",
    depH: "11:00",
    arrH: "14:30",
    dur: "3h30",
    depart: "Douala",
    arrive: "Yaoundé",
    depStop: "Gare Centrale",
    arrStop: "Gare Centrale",
    price: 5000,
    seats: 0,
    total: 32,
    rating: 3.5,
    reviews: 67,
    status: "full",
    amenities: ["❄️"],
  },
  {
    id: "4",
    agency: "Tonton Express",
    code: "TE",
    color: "#0A1628",
    depH: "13:00",
    arrH: "16:30",
    dur: "3h30",
    depart: "Douala",
    arrive: "Yaoundé",
    depStop: "Bonabéri",
    arrStop: "Gare Centrale",
    price: 4800,
    seats: 22,
    total: 32,
    rating: 4.5,
    reviews: 156,
    status: "open",
    amenities: ["❄️", "🧳"],
  },
  {
    id: "5",
    agency: "Cerise Express",
    code: "CE",
    color: "#E91E63",
    depH: "15:00",
    arrH: "18:30",
    dur: "3h30",
    depart: "Douala",
    arrive: "Yaoundé",
    depStop: "Gare Centrale",
    arrStop: "Gare Centrale",
    price: 5500,
    seats: 18,
    total: 35,
    rating: 4.9,
    reviews: 312,
    status: "open",
    amenities: ["❄️", "🧳", "🔌", "🍽️"],
  },
  {
    id: "6",
    agency: "Général Express",
    code: "GE",
    color: "#1DB954",
    depH: "17:30",
    arrH: "21:00",
    dur: "3h30",
    depart: "Douala",
    arrive: "Yaoundé",
    depStop: "Gare Centrale",
    arrStop: "Gare Centrale",
    price: 5000,
    seats: 9,
    total: 32,
    rating: 4.2,
    reviews: 128,
    status: "open",
    amenities: ["❄️", "🧳"],
  },
];

export function fees(amount: number) {
  return Math.round(amount * 0.05);
}

export function fmt(n: number) {
  return n.toLocaleString("fr-FR");
}
